version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    parallelism: 4
    working_directory: /go/src/github.com/mylockerteam/alog
    steps:
      - checkout
      - run: |
          go get -v -t -d ./...
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run:
          name: Build Success
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)